In [16]:
import cerberus
import pandas as pd
import pyranges as pr

In [11]:
# ref = '../data/pseudomasked_genomic_flair_guided/cerb/ref/HG03732_1.h5'
# ca = cerberus.read(ref)

In [17]:
ic_file = '../data/pseudomasked_genomic_flair_guided/cerb/ref/ref_ic.tsv'
ic = pd.read_csv(ic_file, sep='\t')

In [18]:
tss.head()

+------------+--------+--------+-------------------+---+---+-----+
| Chromosome
(category)            |        Start
(int64) |        End
(int64) | Name
(object)                   | Score
(object)   | Strand
(category)   | +4
...     |
|------------+--------+--------+-------------------+---+---+-----|
| GL000008.2 |  83306 |  83446 | ENSG00000296732_1 | . | + | ... |
| GL000008.2 |  85532 |  85583 | ENSG00000296732_2 | . | + | ... |
| GL000008.2 | 208519 | 208637 | ENSG00000296756_1 | . | - | ... |
| GL000008.2 | 170299 | 170454 | ENSG00000296775_1 | . | - | ... |
| GL000009.2 |  35368 |  35419 | ENSG00000296902_1 | . | + | ... |
| GL000009.2 |   5095 |   5222 | ENSG00000297619_1 | . | + | ... |
| GL000009.2 |  82811 |  82862 | ENSG00000306744_1 | . | + | ... |
| GL000009.2 |  43268 |  43322 | ENSG00000306767_1 | . | + | ... |
+------------+--------+--------+-------------------+---+---+-----+
Stranded PyRanges object has 8 rows and 10 columns from 2 chromosomes.
For printing, the PyRanges was sorted on Chromosome and Strand.
4 hidden columns: ThickStart, ThickEnd, ItemRGB, BlockCount